<?php

/**
 * @file
 * Merge duplicate rows in group to one row.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_preprocess_hook().
 *
 * @internal
 */
function views_table_rowspan_preprocess_views_view_table(&$vars): void {
  $view = $vars['view'];
  if (isset($view->rowspan)) {
    foreach ($view->rowspan as $field_name => $rowspan) {
      foreach ($rowspan as $row_index => $num_span) {
        /** @var \Drupal\Core\Template\Attribute $attributes */
        $attributes = &$vars['rows'][$row_index]['columns'][$field_name]['attributes'];
        $attributes->setAttribute('rowspan', count($num_span));
        $attributes->addClass('cell-rowspan');

        // Hide other columns.
        array_shift($num_span);
        foreach ($num_span as $row_span_index) {
          $attributes = &$vars['rows'][$row_span_index]['columns'][$field_name]['attributes'];
          $attributes->setAttribute('style', 'display:none');
        }
      }
    }
  }
}
